### ISSUE TITLE
Add homepage with basic structure for whatsapp

### ISSUE THREAD

**Issue by AR553** [AR553/Whatsapp-Clone#1]

**Comment by EANimesha** [comment]
I like to work in this. Assign me

**Comment by AR553** [comment]
> I like to work in this. Assign me

Basic structure is done but you can work on homepage. You can add camera button and tab. Also the chat tiles. Thanks in advance.

**Comment by EANimesha** [comment]
> > I like to work in this. Assign me
> 
> Basic structure is done but you can work on homepage. You can add camera button and tab. Also the chat tiles. Thanks in advance.

ok

**Comment by EANimesha** [comment]
@AR553 I send a PR. can you check?

**Comment by EANimesha** [comment]
Hello @AR553

**Comment by AR553** [comment]
Merged, great work man. Thank you for your contribution
